import user1 from "./assets/products/Dell1.jpg";
import user2 from "./assets/products/Dell2.jpg";
import user3 from "./assets/products/Dell3.jpg";
import user4 from "./assets/products/Dell4.jpg";
import user5 from "./assets/products/mobile1.jpg";
import user6 from "./assets/products/mobile2.jpg";
import user7 from "./assets/products/Tv11.png";
import user8 from "./assets/products/Tv3.jpg";
import user9 from "./assets/products/fur1.jpg";
import user10 from "./assets/products/fur2.jpg";
// import user11 from "./assets/products/Dec1.jpg";
import user12 from "./assets/products/Dec2.jpg";
import user13 from "./assets/products/men1.jpg";
import user14 from "./assets/products/men2.jpg";
import user15 from "./assets/products/women1.jpg";
import user16 from "./assets/products/wo12.jpg";



const products = {
  Electronics: {
    Computers: [
      { id: 1, 
        title:'Computers',
        name: 'Lenovo Thinkpad', 
        model: "Inspiron 15",
        price: "899.99",
        category: "Electronics",
        description: "A versatile laptop with powerful performance and a sleek design.",
        image: user1,
     },
      { id: 2, 
        name: 'Macbook Pro',
        model: "Inspiron 15",
        price: "899.99",
        category: "Electronics",
        description: "A versatile laptop with powerful performance and a sleek design.",
        image: user2,
       },
      { id: 3,
         name: 'Dell XPS',
         model: "Inspiron 15",
         price: "899.99",
         category: "Electronics",
         description: "A versatile laptop with powerful performance and a sleek design.",
         image: user3,
         },
      { id: 4, name: 
        'HP Pavilion',
        model: "Inspiron 15",
        price: "899.99",
        category: "Electronics",
        description: "A versatile laptop with powerful performance and a sleek design.",
        image: user4,
     }
    ],
    Phones: [
        { id: 1, 
            title:'Computers',
            name: 'Lenovo Thinkpad', 
            model: "Inspiron 15",
            price: "899.99",
            category: "Electronics",
            description: "A versatile laptop with powerful performance and a sleek design.",
            image: user5,
         },
          { id: 2, 
            name: 'Macbook Pro',
            model: "Inspiron 15",
            price: "899.99",
            category: "Electronics",
            description: "A versatile laptop with powerful performance and a sleek design.",
            image: user5,
           },
          { id: 3,
             name: 'Dell XPS',
             model: "Inspiron 15",
             price: "899.99",
             category: "Electronics",
             description: "A versatile laptop with powerful performance and a sleek design.",
             image: user6,
             }   
    ],
    Tv: [
        { id: 1, 
            title:'Computers',
            name: 'Lenovo Thinkpad', 
            model: "Inspiron 15",
            price: "899.99",
            category: "Electronics",
            description: "A versatile laptop with powerful performance and a sleek design.",
            image: user7,
         },
          { id: 2, 
            name: 'Macbook Pro',
            model: "Inspiron 15",
            price: "899.99",
            category: "Electronics",
            description: "A versatile laptop with powerful performance and a sleek design.",
            image: user8,
           },
          { id: 3,
             name: 'Dell XPS',
             model: "Inspiron 15",
             price: "899.99",
             category: "Electronics",
             description: "A versatile laptop with powerful performance and a sleek design.",
             image: user7,
             },
          { id: 4, name: 
            'HP Pavilion',
            model: "Inspiron 15",
            price: "899.99",
            category: "Electronics",
            description: "A versatile laptop with powerful performance and a sleek design.",
            image: user4,
         }
    ],
  },
  Home: {
    Furniture: [
        { id: 1, 
            title:'Computers',
            name: 'Lenovo Thinkpad', 
            model: "Inspiron 15",
            price: "899.99",
            category: "Electronics",
            description: "A versatile laptop with powerful performance and a sleek design.",
            image: user9,
         },
          { id: 2, 
            name: 'Macbook Pro',
            model: "Inspiron 15",
            price: "899.99",
            category: "Electronics",
            description: "A versatile laptop with powerful performance and a sleek design.",
            image: user10,
           },
          { id: 3,
             name: 'Dell XPS',
             model: "Inspiron 15",
             price: "899.99",
             category: "Electronics",
             description: "A versatile laptop with powerful performance and a sleek design.",
             image: user12,
             } 
    ],
    Decorations: [
        { id: 1, 
            title:'Computers',
            name: 'Lenovo Thinkpad', 
            model: "Inspiron 15",
            price: "899.99",
            category: "Electronics",
            description: "A versatile laptop with powerful performance and a sleek design.",
            image: user12,
         },
          { id: 2, 
            name: 'Macbook Pro',
            model: "Inspiron 15",
            price: "899.99",
            category: "Electronics",
            description: "A versatile laptop with powerful performance and a sleek design.",
            image: user9,
           },
          { id: 3,
             name: 'Dell XPS',
             model: "Inspiron 15",
             price: "899.99",
             category: "Electronics",
             description: "A versatile laptop with powerful performance and a sleek design.",
             image: user10,
             },
          { id: 4, name: 
            'HP Pavilion',
            model: "Inspiron 15",
            price: "899.99",
            category: "Electronics",
            description: "A versatile laptop with powerful performance and a sleek design.",
            image: user12,
         }
    ],
  },
  Fashion: {
    Mens: [
        { id: 1, 
            title:'Computers',
            name: 'Lenovo Thinkpad', 
            model: "Inspiron 15",
            price: "899.99",
            category: "Electronics",
            description: "A versatile laptop with powerful performance and a sleek design.",
            image: user13,
         },
          { id: 2, 
            name: 'Macbook Pro',
            model: "Inspiron 15",
            price: "899.99",
            category: "Electronics",
            description: "A versatile laptop with powerful performance and a sleek design.",
            image: user14,
           },
           { id: 3, 
            name: 'Macbook Pro',
            model: "Inspiron 15",
            price: "899.99",
            category: "Electronics",
            description: "A versatile laptop with powerful performance and a sleek design.",
            image: user13,
           }
    ],
    Womens: [
        { id: 1, 
            title:'Computers',
            name: 'Lenovo Thinkpad', 
            model: "Inspiron 15",
            price: "899.99",
            category: "Electronics",
            description: "A versatile laptop with powerful performance and a sleek design.",
            image: user15,
         },
         { id: 3,
            name: 'Dell XPS',
            model: "Inspiron 15",
            price: "899.99",
            category: "Electronics",
            description: "A versatile laptop with powerful performance and a sleek design.",
            image: user16,
            },
         { id: 4, name: 
           'HP Pavilion',
           model: "Inspiron 15",
           price: "899.99",
           category: "Electronics",
           description: "A versatile laptop with powerful performance and a sleek design.",
           image: user15,
        }
    ],
  },
  Books: {
    Fiction: [
        { id: 1, 
            title:'Computers',
            name: 'Lenovo Thinkpad', 
            model: "Inspiron 15",
            price: "899.99",
            category: "Electronics",
            description: "A versatile laptop with powerful performance and a sleek design.",
            image: user1,
         },
          { id: 2, 
            name: 'Macbook Pro',
            model: "Inspiron 15",
            price: "899.99",
            category: "Electronics",
            description: "A versatile laptop with powerful performance and a sleek design.",
            image: user2,
           },
          { id: 3,
             name: 'Dell XPS',
             model: "Inspiron 15",
             price: "899.99",
             category: "Electronics",
             description: "A versatile laptop with powerful performance and a sleek design.",
             image: user3,
             },
          { id: 4, name: 
            'HP Pavilion',
            model: "Inspiron 15",
            price: "899.99",
            category: "Electronics",
            description: "A versatile laptop with powerful performance and a sleek design.",
            image: user4,
         }
    ],
    NonFiction: [
        { id: 1, 
            title:'Computers',
            name: 'Lenovo Thinkpad', 
            model: "Inspiron 15",
            price: "899.99",
            category: "Electronics",
            description: "A versatile laptop with powerful performance and a sleek design.",
            image: user1,
         },
          { id: 2, 
            name: 'Macbook Pro',
            model: "Inspiron 15",
            price: "899.99",
            category: "Electronics",
            description: "A versatile laptop with powerful performance and a sleek design.",
            image: user2,
           },
           { id: 3, 
            name: 'Macbook Pro',
            model: "Inspiron 15",
            price: "899.99",
            category: "Electronics",
            description: "A versatile laptop with powerful performance and a sleek design.",
            image: user2,
           },
    ],
  },
};

export default products;